"""Add OTPRateLimit tableq

Revision ID: 0a0b00d6f04c
Revises: 050fb84de241
Create Date: 2024-12-21 12:39:16.089486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a0b00d6f04c'
down_revision: Union[str, None] = '050fb84de241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otpratelimit',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_request', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otpratelimit')
    # ### end Alembic commands ###
