"""Add user, subscription, and company relationships

Revision ID: 1a8629c1ee47
Revises: 9d5c9312fc14
Create Date: 2024-12-22 11:33:08.009804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8629c1ee47'
down_revision: Union[str, None] = '9d5c9312fc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
