"""Add soft deletion status to Company model, Replace is_approved and is_active with status in Company

Revision ID: 25e1025b1a65
Revises: a34acbba534f
Create Date: 2025-01-05 12:41:29.058459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25e1025b1a65'
down_revision: Union[str, None] = 'a34acbba534f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('last_year_local_score', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('local_content_certificate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Add 'status' column with a default value for existing rows
    op.add_column(
        'company',
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending')
    )
    # Drop 'is_approved' and 'is_active' columns
    op.drop_column('company', 'is_approved')
    op.drop_column('company', 'is_active')

    # Optionally remove the default constraint on 'status' (cleanup after setting values)
    op.alter_column('company', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Add 'is_active' and 'is_approved' with a default value to avoid NULL errors
    op.add_column('company', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('company', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Remove the 'status' column
    op.drop_column('company', 'status')
    op.drop_column('company', 'local_content_certificate')
    op.drop_column('company', 'last_year_local_score')

    # Optionally remove the default constraint on 'is_active' and 'is_approved'
    op.alter_column('company', 'is_active', server_default=None)
    op.alter_column('company', 'is_approved', server_default=None)
