"""Add reset_otp fields to User

Revision ID: 35a4ea1817dc
Revises: 0a0b00d6f04c
Create Date: 2024-12-21 23:50:30.608584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35a4ea1817dc'
down_revision: Union[str, None] = '0a0b00d6f04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_otp_expiry')
    op.drop_column('user', 'reset_otp')
    # ### end Alembic commands ###
