"""Add company view tracking, notifications, and status updates - fix

Revision ID: 89296dbb16dc
Revises: 3df4fb305c11
Create Date: 2025-01-31 14:40:37.678062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89296dbb16dc'
down_revision: Union[str, None] = '3df4fb305c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
