"""Added plan_id to Payment table

Revision ID: 95c02bd2690c
Revises: 777b8b771db0
Create Date: 2025-02-04 08:48:16.646924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c02bd2690c'
down_revision: Union[str, None] = '777b8b771db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment', 'subscriptionplan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'plan_id')
    # ### end Alembic commands ###
