"""Fix relationships in Subscription model

Revision ID: 9653d04f0113
Revises: f01dfacadf95
Create Date: 2025-02-02 13:01:37.002171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9653d04f0113'
down_revision: Union[str, None] = 'f01dfacadf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('payment', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment', 'subscription', ['subscription_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'subscription_id')
    op.drop_column('payment', 'user_id')
    # ### end Alembic commands ###
