"""Fix Notification model: Change user_id to recipient_id

Revision ID: 96d32242d18f
Revises: 5288794db470
Create Date: 2025-01-31 15:11:33.693250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d32242d18f'
down_revision: Union[str, None] = '5288794db470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
