"""Add user, subscription, and company relationships

Revision ID: 9d5c9312fc14
Revises: a0ec51f55066
Create Date: 2024-12-22 11:32:37.115276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5c9312fc14'
down_revision: Union[str, None] = 'a0ec51f55066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
