"""Update Company model for ARRAY fields

Revision ID: a34acbba534f
Revises: bc279d434396
Create Date: 2025-01-05 12:27:44.805615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a34acbba534f'
down_revision: Union[str, None] = 'bc279d434396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company', sa.Column('awards', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('company', sa.Column('sectors', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'sectors')
    op.drop_column('company', 'awards')
    op.drop_column('company', 'description')
    # ### end Alembic commands ###
