"""Fix SubscriptionPlan Auto-Increment

Revision ID: f01dfacadf95
Revises: da7406e453f1
Create Date: 2025-02-02 12:36:30.664597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01dfacadf95'
down_revision: Union[str, None] = 'da7406e453f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_subscription_plan', 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'subscriptionplan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key('fk_subscription_plan', 'subscription', 'subscriptionplan', ['plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
